name: device_frame
description: Mockups for common devices.
version: 1.0.2
homepage: https://github.com/aloisdeniel/flutter_device_preview/device_frame
publish_to: https://pub.trugman.com/
# publish_to: https://dart.pkg.jetbrains.space/trugman/p/main/dart/

environment:
  sdk: ^3.10.1

dependencies:
  freezed_annotation: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.9.0
  freezed: ^3.1.0
  flutter_lints: ^1.0.4
  xml: ^5.3.1
  recase: ^4.0.0
