name: device_preview
version: 1.0.0
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview
publish_to: https://pub.trugman.com/udi/stiebals32/

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.1
  device_frame:
    hosted: https://pub.trugman.com/udi/stiebals32/
    version: ^1.0.0
  freezed_annotation: ^2.0.1
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^1.0.4
  build_runner: ^2.1.4
  freezed: ^2.0.2
  json_serializable: ^6.1.0
  analyzer: ^3.0.0

#dependency_overrides:
#  device_frame:
#    path: ../device_frame
